### ISSUE TITLE
Trailing slash in issuer

### ISSUE THREAD

**Issue by michielbdejong** [pdsinterop/php-solid-server#22]
See https://travis-ci.com/github/pdsinterop/php-solid-server/builds/190957568#L2133
It should not have a trailing slash there.
See also https://github.com/pdsinterop/php-solid-server/commit/3299c4e2365c7ea0d0fa9c080debf03f1b74b87f

**Comment by Potherca** [comment]
I encountered the same issue, have a fix pending. Ideally this bug will go away when we replace the hard-coded bit with dynamic host-name retrieval.

**Comment by Potherca** [comment]
A first solution has been implemented in https://github.com/pdsinterop/php-solid-server/commit/9b2c3e0d0d80c5a380c64c126b94cb4fb32097a2 by retrieving the domain form `$_SERVER['REQUEST_URI']`, this can later be replaced by a config setting if/when needed.

Closing this issue for now.
