### ISSUE TITLE
possible helpful codebase

### ISSUE THREAD

**Issue by melvincarvalho** [pdsinterop/php-solid-server#3]
Back in the day this was the solid reference implementation by @deiu .  It worked really well

https://github.com/linkeddata/ldphp

Obviously very very old now

But possibly some ideas or patterns you could reuse

It would not surprise me if it still worked tho! :)

**Comment by michielbdejong** [comment]
Thank @melvincarvalho! Tim had the same suggestion. For the webid-provider part we're implementing the new DPop login flow, so we'll be contributing that upstream to https://github.com/thephpleague/oauth2-server.

For the LDP part we're building https://github.com/pdsinterop/flysystem-rdf. Created an issue there about maybe using parts of php5-librdf: https://github.com/pdsinterop/flysystem-rdf/issues/1.
For the WAC part we might learn from https://github.com/linkeddata/ldphp/blob/master/www/inc/class/WAC.php but it doesn't look like it implements the entire current WAC spec. That code is 6 years old, predates the start of the Solid project! :)

Anyway, thanks for the suggestion! I'll close this issue now and leave just the follow-up one in the flysystem-rdf repo.
